import { BrowserWindow, dialog } from 'electron';
import path from 'node:path';
import type {
  ConnectionConfig,
  ConnectionHistoryItem,
  DatabaseConnector,
  DatabaseSchema,
  ModelChatMessage,
  ModelProvider,
  ModelProviderKind,
  PersistedChatSession,
  PersistedSettings,
  QueryResult
} from '../shared/types.js';
import type { OpenDialogOptions } from 'electron';
import { ElasticsearchConnector } from './connectors/ElasticsearchConnector.js';
import { SQLiteConnector } from './connectors/SQLiteConnector.js';
import {
  buildLocalAssistantResponse,
  buildResultAnalysisPrompt,
  buildSystemPrompt,
  extractQueryBlock,
  removeSqlBlocks,
  summarizeQueryResult
} from './assistant/localAssistant.js';
import { modelProviders } from './model/providers.js';
import { AppStore } from './storage/AppStore.js';

export class IpcController {
  private connector: DatabaseConnector | null = null;
  private schema: DatabaseSchema | null = null;

  constructor(private readonly store: AppStore) {}

  async chooseSqliteFile(): Promise<ConnectionConfig | null> {
    const window = BrowserWindow.getFocusedWindow() ?? BrowserWindow.getAllWindows()[0];
    const dialogOptions: OpenDialogOptions = {
      title: 'Choose SQLite Database',
      properties: ['openFile'],
      filters: [
        { name: 'SQLite databases', extensions: ['db', 'sqlite', 'sqlite3'] },
        { name: 'All files', extensions: ['*'] }
      ]
    };
    const result = window
      ? await dialog.showOpenDialog(window, dialogOptions)
      : await dialog.showOpenDialog(dialogOptions);

    const filePath = result.filePaths[0];
    if (result.canceled || !filePath) {
      return null;
    }

    return {
      id: crypto.randomUUID(),
      kind: 'sqlite',
      label: path.basename(filePath),
      databasePath: filePath,
      createdAt: new Date().toISOString()
    };
  }

  async connect(config: ConnectionConfig): Promise<DatabaseSchema> {
    if (config.kind !== 'sqlite' && config.kind !== 'elasticsearch') {
      throw new Error(`${config.kind} is not implemented in this MVP.`);
    }
    const hydratedConfig = this.store.hydrateConnectionSecrets(config);
    this.connector?.close();
    const connector = hydratedConfig.kind === 'elasticsearch'
      ? new ElasticsearchConnector()
      : new SQLiteConnector();
    await connector.connect(hydratedConfig);
    this.connector = connector;
    this.schema = await connector.introspect();
    this.store.saveConnection(hydratedConfig);
    return this.schema;
  }

  async getSchema(): Promise<DatabaseSchema | null> {
    return this.schema;
  }

  async sendChat(messages: ModelChatMessage[]) {
    const settings = this.store.loadSettings();
    const executionMode = settings.safeMode ? 'safe' : 'manual';
    const apiKey = this.store.getApiKey(settings.provider);
    const schemaContext = this.connector ? await this.connector.getContextForPrompt() : 'No database is connected.';
    const chatHistory = messages
      .filter((message) => message.role === 'user' || message.role === 'assistant')
      .map((message) => ({ ...message, content: removeSqlBlocks(message.content) }))
      .slice(-16);
    const prompt = [...chatHistory].reverse().find((message) => message.role === 'user')?.content ?? '';

    if (!apiKey) {
      const local = buildLocalAssistantResponse(prompt, this.schema);
      const queryResult = local.query && this.connector && local.query.validation.safe
        ? await this.connector.executeQuery(local.query.query, executionMode)
        : undefined;
      return {
        message: {
          id: crypto.randomUUID(),
          role: 'assistant',
          content: queryResult ? summarizeQueryResult(queryResult) : removeSqlBlocks(local.content),
          createdAt: new Date().toISOString()
        },
        generatedQuery: local.query,
        queryResult
      };
    }

    const provider = modelProviders[settings.provider];
    const content = await provider.sendChat([
      { role: 'system', content: buildSystemPrompt(schemaContext, this.schema?.kind ?? 'sqlite', executionMode) },
      ...chatHistory
    ], {
      model: settings.model || provider.defaultModel,
      apiKey,
      temperature: 0.2
    });
    const query = extractQueryBlock(content, this.schema?.kind ?? 'sqlite');
    const generatedQuery = query && this.connector ? {
      query,
      explanation: 'Generated by the selected model provider.',
      validation: this.connector.validateQuery(query, executionMode)
    } : undefined;
    const queryResult = generatedQuery?.validation.safe && this.connector
      ? await this.connector.executeQuery(generatedQuery.query, executionMode)
      : undefined;
    const responseContent = queryResult && generatedQuery
      ? await this.buildResultAwareResponse(provider, settings.model || provider.defaultModel, apiKey, chatHistory, generatedQuery.query, queryResult)
      : generatedQuery && !generatedQuery.validation.safe
        ? `I found a query for that, but validation did not allow it: ${generatedQuery.validation.reason}`
        : removeSqlBlocks(content);

    return {
      message: {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: responseContent,
        createdAt: new Date().toISOString()
      },
      generatedQuery,
      queryResult
    };
  }

  private async buildResultAwareResponse(
    provider: ModelProvider,
    model: string,
    apiKey: string,
    chatHistory: ModelChatMessage[],
    query: string,
    result: QueryResult
  ): Promise<string> {
    const resultContext = JSON.stringify({
      columns: result.columns,
      rowCount: result.rowCount,
      elapsedMs: result.elapsedMs,
      rows: result.rows.slice(0, 25)
    }, null, 2);

    try {
      const content = await provider.sendChat([
        {
          role: 'system',
          content: buildResultAnalysisPrompt(this.schema?.kind ?? 'sqlite', this.store.loadSettings().safeMode ? 'safe' : 'manual')
        },
        ...chatHistory,
        {
          role: 'assistant',
          content: [
            'Executed query:',
            query,
            '',
            'Query result JSON:',
            resultContext
          ].join('\n')
        }
      ], {
        model,
        apiKey,
        temperature: 0.2
      });

      return removeSqlBlocks(content) || summarizeQueryResult(result);
    } catch {
      return summarizeQueryResult(result);
    }
  }

  loadSettings(): PersistedSettings & { hasApiKey: boolean } {
    const settings = this.store.loadSettings();
    return {
      ...settings,
      hasApiKey: this.store.hasApiKey(settings.provider)
    };
  }

  saveSettings(settings: PersistedSettings): void {
    this.store.saveSettings(settings);
  }

  saveApiKey(provider: ModelProviderKind, apiKey: string): void {
    this.store.saveApiKey(provider, apiKey);
  }

  async listModels(provider: ModelProviderKind) {
    return modelProviders[provider].listModels(this.store.getApiKey(provider) ?? undefined);
  }

  listChatSessions(): PersistedChatSession[] {
    return this.store.listChatSessions();
  }

  saveChatSession(session: PersistedChatSession): PersistedChatSession {
    return this.store.saveChatSession(session);
  }

  deleteChatSession(id: string): void {
    this.store.deleteChatSession(id);
  }

  listConnections(): ConnectionHistoryItem[] {
    return this.store.listConnections();
  }

  deleteConnection(id: string): void {
    this.store.deleteConnection(id);
  }

  requireConnector(): DatabaseConnector {
    if (!this.connector) {
      throw new Error('No database is connected.');
    }
    return this.connector;
  }
}
