import { BrowserWindow, dialog } from 'electron';
import path from 'node:path';
import type {
  ConnectionConfig,
  DatabaseConnector,
  DatabaseSchema,
  ModelChatMessage,
  ModelProviderKind,
  PersistedSettings
} from '../shared/types.js';
import type { OpenDialogOptions } from 'electron';
import { SQLiteConnector } from './connectors/SQLiteConnector.js';
import { buildLocalAssistantResponse, buildSystemPrompt, extractSqlBlock } from './assistant/localAssistant.js';
import { modelProviders } from './model/providers.js';
import { AppStore } from './storage/AppStore.js';

export class IpcController {
  private connector: DatabaseConnector | null = null;
  private schema: DatabaseSchema | null = null;

  constructor(private readonly store: AppStore) {}

  async chooseSqliteFile(): Promise<ConnectionConfig | null> {
    const window = BrowserWindow.getFocusedWindow() ?? BrowserWindow.getAllWindows()[0];
    const dialogOptions: OpenDialogOptions = {
      title: 'Choose SQLite Database',
      properties: ['openFile'],
      filters: [
        { name: 'SQLite databases', extensions: ['db', 'sqlite', 'sqlite3'] },
        { name: 'All files', extensions: ['*'] }
      ]
    };
    const result = window
      ? await dialog.showOpenDialog(window, dialogOptions)
      : await dialog.showOpenDialog(dialogOptions);

    const filePath = result.filePaths[0];
    if (result.canceled || !filePath) {
      return null;
    }

    return {
      id: crypto.randomUUID(),
      kind: 'sqlite',
      label: path.basename(filePath),
      databasePath: filePath,
      createdAt: new Date().toISOString()
    };
  }

  async connect(config: ConnectionConfig): Promise<DatabaseSchema> {
    if (config.kind !== 'sqlite') {
      throw new Error(`${config.kind} is not implemented in this MVP.`);
    }
    this.connector?.close();
    const connector = new SQLiteConnector();
    await connector.connect(config);
    this.connector = connector;
    this.schema = await connector.introspect();
    return this.schema;
  }

  async getSchema(): Promise<DatabaseSchema | null> {
    return this.schema;
  }

  async sendChat(messages: ModelChatMessage[]) {
    const settings = this.store.loadSettings();
    const apiKey = this.store.getApiKey(settings.provider);
    const schemaContext = this.connector ? await this.connector.getContextForPrompt() : 'No database is connected.';
    const chatHistory = messages
      .filter((message) => message.role === 'user' || message.role === 'assistant')
      .slice(-16);
    const prompt = [...chatHistory].reverse().find((message) => message.role === 'user')?.content ?? '';

    if (!apiKey) {
      const local = buildLocalAssistantResponse(prompt, this.schema);
      return {
        message: {
          id: crypto.randomUUID(),
          role: 'assistant',
          content: local.content,
          createdAt: new Date().toISOString()
        },
        generatedQuery: local.query
      };
    }

    const provider = modelProviders[settings.provider];
    const content = await provider.sendChat([
      { role: 'system', content: buildSystemPrompt(schemaContext) },
      ...chatHistory
    ], {
      model: settings.model || provider.defaultModel,
      apiKey,
      temperature: 0.2
    });
    const query = extractSqlBlock(content);

    return {
      message: {
        id: crypto.randomUUID(),
        role: 'assistant',
        content,
        createdAt: new Date().toISOString()
      },
      generatedQuery: query && this.connector ? {
        query,
        explanation: 'Generated by the selected model provider.',
        validation: this.connector.validateQuery(query, 'safe')
      } : undefined
    };
  }

  loadSettings(): PersistedSettings & { hasApiKey: boolean } {
    const settings = this.store.loadSettings();
    return {
      ...settings,
      hasApiKey: this.store.hasApiKey(settings.provider)
    };
  }

  saveSettings(settings: PersistedSettings): void {
    this.store.saveSettings(settings);
  }

  saveApiKey(provider: ModelProviderKind, apiKey: string): void {
    this.store.saveApiKey(provider, apiKey);
  }

  async listModels(provider: ModelProviderKind) {
    return modelProviders[provider].listModels(this.store.getApiKey(provider) ?? undefined);
  }

  requireConnector(): DatabaseConnector {
    if (!this.connector) {
      throw new Error('No database is connected.');
    }
    return this.connector;
  }
}
